[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "raspberry-pi"
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["${INFLUX_URL}"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"

[[inputs.mqtt_consumer]]
  servers = ["${MQTT_SERVER}"]
  topics = ["${MQTT_TOPIC}"]
  client_id = "smart-env-telegraf"
  qos = 0
  connection_timeout = "30s"
  max_reconnect_interval = "30s"
  persistent_session = false
  username = "${MQTT_USERNAME}"
  password = "${MQTT_PASSWORD}"
  topic_tag = "topic"
  data_format = "json_v2"

  [inputs.mqtt_consumer.tags]
    device = "esp32c3-supermini"
    sensor = "bme680"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "environment"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temperature_c"
      rename = "temperature_c"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "humidity_percent"
      rename = "humidity_percent"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "pressure_hpa"
      rename = "pressure_hpa"
      type = "float"
